apiVersion: v1
kind: Namespace
metadata:
  # This name will be overridden by environment-specific kustomizations
  name: guestbook-placeholder
  # We could add common labels/annotations for all namespaces here if needed
